version: '3'
services:
  db:
    image: postgres:13.8-alpine3.16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
  api:
    build:
      context: ./api
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    command: npm run start
    depends_on:
      - db
    volumes:
      - ./api:/app
      - /app/node_modules